server:
  port: 8089

discord:
  token: MTEzMzcyMDg1NDk3OTY5MDUzNg.GGnEo5.Yd39o8T_-i-sTDGdNlIIuCbF8xWl6palr_ta4k

chat-gpt:
  model: gpt-3.5-turbo
  uri: https://api.openai.com/v1/chat/completions
  token-3.5: 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

spring:
  datasource:
    url: jdbc:h2:~/discordBot;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true