server:
  port: 8089

discord:
  token: private

chat-gpt:
  model: gpt-3.5-turbo
  uri: https://api.openai.com/v1/chat/completions
  token-3.5: private

spring:
  datasource:
    url: jdbc:h2:~/discordBot;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true